# Generated by Django 2.1.5 on 2019-02-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubble_amount', models.IntegerField()),
                ('bubble_cartFilled', models.BooleanField()),
                ('bubble_shipped', models.BooleanField()),
                ('bubble_start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('items_name', models.CharField(max_length=200)),
                ('items_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_TimeDate', models.DateTimeField(auto_now_add=True)),
                ('orders_BubbleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bubble')),
                ('orders_ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
                ('orders_UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_name', models.CharField(max_length=200)),
                ('retail_url', models.CharField(max_length=200)),
                ('retail_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retail_duration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='items_RetailerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.retailer'),
        ),
        migrations.AddField(
            model_name='bubble',
            name='bubble_RetailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.retailer'),
        ),
        migrations.AddField(
            model_name='bubble',
            name='bubble_UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
